### ISSUE TITLE
to-do lists

### ISSUE THREAD

**Issue by YangyangFu** [YangyangFu/dissertation#2]
9/2/2019
- [ ] rephrase frequency regulation in PJM 
- [ ] update research proposal for future work
- [ ] update presentation slides
